f = r'src\main\resources\public\dashboard.html'
data = open(f, 'r', encoding='utf-8').read()

# Comprehensive mapping of garbled -> correct Vietnamese
replacements = [
    # Title
    ('Quáº£n lÃ½ Váº­t liá»\u0087u XÃ¢y dá»±ng', 'Quản lý Vật liệu Xây dựng'),

    # Sidebar / common
    ('\u0097ï¸\uFFFD VLXD', '🏗️ VLXD'),
    ('ðŸ—ï¸', '🏗️'),
    ('ðŸ"Š', '📊'),
    ('ðŸ›'', '🛒'),
    ('ðŸ"‹', '📋'),
    ('ðŸ'³', '💳'),
    ('â†©ï¸', '↩️'),
    ('ðŸ"¦', '📦'),
    ('ðŸ·ï¸', '🏷️'),
    ('ðŸ­', '🏭'),
    ('ðŸš›', '🚛'),
    ('ðŸ'¥', '👥'),
    ('ðŸŽ', '🎁'),
    ('ðŸ'"', '👔'),
    ('ðŸ"'', '🔑'),
    ('ðŸ"„', '🔄'),
    ('ðŸ"', '🔍'),
    ('âœ…', '✅'),
    ('ðŸ—'ï¸', '🗑️'),

    # Vietnamese words - ordered longest first to avoid partial matches
    ('Tráº¡ng thÃ¡i Ä\u0091á»\u0093ng bá»\u0099', 'Trạng thái đồng bộ'),
    ('Äang kiá»\u0083m tra...', 'Đang kiểm tra...'),
    ('Tá»\u0095ng quan', 'Tổng quan'),
    ('BÃ¡n hÃ\xa0ng', 'Bán hàng'),
    ('Ä\x90Æ¡n hÃ\xa0ng', 'Đơn hàng'),
    ('Thanh toÃ¡n', 'Thanh toán'),
    ('Tráº£ hÃ\xa0ng', 'Trả hàng'),
    ('Sáº£n pháº©m', 'Sản phẩm'),
    ('Danh má»¥c', 'Danh mục'),
    ('Kho hÃ\xa0ng', 'Kho hàng'),
    ('NhÃ\xa0 cung cáº¥p', 'Nhà cung cấp'),
    ('KhÃ¡ch hÃ\xa0ng', 'Khách hàng'),
    ('Khuyáº¿n mÃ£i', 'Khuyến mãi'),
    ('NhÃ¢n sá»±', 'Nhân sự'),
    ('TÃ\xa0i khoáº£n', 'Tài khoản'),
    ('Ä\x90iá»\u0081u chuyá»\u0083n', 'Điều chuyển'),
    ('Ä\x90Äƒng xuáº¥t', 'Đăng xuất'),
    ('Táº£i láº¡i', 'Tải lại'),
    ('Táº£i lÃ¡i', 'Tải lại'),
    ('dá»¯ liá»\u0087u', 'dữ liệu'),

    # Table headers and common UI
    ('MÃ£ SP', 'Mã SP'),
    ('TÃªn sáº£n pháº©m', 'Tên sản phẩm'),
    ('TÃªn', 'Tên'),
    ('Ä\x90VT', 'ĐVT'),
    ('GiÃ¡', 'Giá'),
    ('Tá»\u0093n', 'Tồn'),
    ('Giá»\u008f hÃ\xa0ng', 'Giỏ hàng'),
    ('ThÃ\xa0nh tiá»\u0081n', 'Thành tiền'),
    ('Táº¡m tÃ­nh', 'Tạm tính'),
    ('Thuáº¿', 'Thuế'),
    ('Giáº£m giÃ¡', 'Giảm giá'),
    ('Tá»\u0095ng', 'Tổng'),
    ('Ghi chÃº', 'Ghi chú'),
    ('Ä\u0091Æ¡n hÃ\xa0ng', 'đơn hàng'),

    # More UI text
    ('MÃ£ Ä\x90H', 'Mã ĐH'),
    ('MÃ£ ÄH', 'Mã ĐH'),
    ('NgÃ\xa0y', 'Ngày'),
    ('Tá»\u0095ng tiá»\u0081n', 'Tổng tiền'),
    ('CÃ´ng ná»£', 'Công nợ'),
    ('Tráº¡ng thÃ¡i', 'Trạng thái'),
    ('Thao tÃ¡c', 'Thao tác'),
    ('PhÆ°Æ¡ng thá»©c', 'Phương thức'),
    ('Sá»\u0091 tiá»\u0081n', 'Số tiền'),
    ('MÃ£ tráº£', 'Mã trả'),
    ('MÃ£ ÄH gá»\u0091c', 'Mã ĐH gốc'),
    ('NgÃ\xa0y tráº£', 'Ngày trả'),
    ('LÃ½ do', 'Lý do'),
    ('Sá»\u0091 tiá»\u0081n hoÃ\xa0n', 'Số tiền hoàn'),
    ('TÃ¬m', 'Tìm'),
    ('tÃªn', 'tên'),
    ('mÃ£', 'mã'),
    ('thÆ°Æ¡ng hiá»\u0087u', 'thương hiệu'),
    ('ThÆ°Æ¡ng hiá»\u0087u', 'Thương hiệu'),
    ('MÃ£ TT', 'Mã TT'),

    # More Vietnamese
    ('má»\u009bi', 'mới'),
    ('XÃ³a giá»\u008f', 'Xóa giỏ'),
    ('XÃ³a', 'Xóa'),
    ('Sá»­a', 'Sửa'),
    ('ThÃªm', 'Thêm'),
    ('sáº£n pháº©m', 'sản phẩm'),
    ('danh má»¥c', 'danh mục'),
    ('nhÃ\xa0 cung cáº¥p', 'nhà cung cấp'),
    ('khÃ¡ch hÃ\xa0ng', 'khách hàng'),
    ('nhÃ¢n viÃªn', 'nhân viên'),
    ('NhÃ¢n viÃªn', 'Nhân viên'),
    ('tÃ\xa0i khoáº£n', 'tài khoản'),

    # Inventory
    ('Kho', 'Kho'),
    ('MÃ£ kho', 'Mã kho'),
    ('Ä\x90á»\u008ba chá»\u0089', 'Địa chỉ'),
    ('SL tá»\u0093n', 'SL tồn'),
    ('SL Ä\u0091Ã£ Ä\u0091áº·t', 'SL đã đặt'),
    ('KhÃ¡ dá»¥ng', 'Khả dụng'),
    ('SL khÃ¡ dá»¥ng', 'SL khả dụng'),
    ('Ä\x90ang hoáº¡t Ä\u0091á»\u0099ng', 'Đang hoạt động'),
    ('NgÆ°ng', 'Ngưng'),
    ('Hoáº¡t Ä\u0091á»\u0099ng', 'Hoạt động'),
    ('hoáº¡t Ä\u0091á»\u0099ng', 'hoạt động'),

    # Customer
    ('Ä\x90iá»\u0083n thoáº¡i', 'Điện thoại'),
    ('Email', 'Email'),
    ('NgÃ\xa0y Ä\u0091Äƒng kÃ½', 'Ngày đăng ký'),
    ('Ä\x90iá»\u0083m', 'Điểm'),
    ('Ä\u0091iá»\u0083m', 'điểm'),

    # Employee
    ('MÃ£ NV', 'Mã NV'),
    ('Há»\u008d tÃªn', 'Họ tên'),
    ('Há»\u008d vÃ\xa0 tÃªn', 'Họ và tên'),
    ('ChÃºc vá»¥', 'Chức vụ'),
    ('Vai trÃ²', 'Vai trò'),
    ('LÆ°Æ¡ng', 'Lương'),
    ('NgÃ\xa0y vÃ\xa0o', 'Ngày vào'),

    # Buttons & misc
    ('Ä\x90Ã£', 'Đã'),
    ('xÃ³a', 'xóa'),
    ('ThÃ nh cÃ´ng', 'Thành công'),
    ('Khá»\u009fi táº¡o', 'Khởi tạo'),
    ('LÆ°u', 'Lưu'),
    ('HÃ ng', 'Hàng'),
    ('Doanh thu', 'Doanh thu'),
    ('ChÃ¡o má»«ng', 'Chào mừng'),
    ('BÃ¡o cÃ¡o', 'Báo cáo'),
    ('Ä\x90Äƒng nháº­p', 'Đăng nhập'),
    ('Ä\u0091Äƒng nháº­p', 'đăng nhập'),
    ('TÃ¬m kiáº¿m', 'Tìm kiếm'),
    ('Máº­t kháº©u', 'Mật khẩu'),
    ('MÃ£', 'Mã'),
    ('Ä\u0091Æ¡n', 'đơn'),
    ('NgÆ°á»\u009di dÃ¹ng', 'Người dùng'),
    ('Cáº­p nháº­t', 'Cập nhật'),
    ('má»\u009di', 'mới'),

    # Promotions
    ('Voucher', 'Voucher'),
    ('GiÃ¡ trá»\u008b', 'Giá trị'),
    ('NgÃ\xa0y báº¯t Ä\u0091áº§u', 'Ngày bắt đầu'),
    ('NgÃ\xa0y káº¿t thÃºc', 'Ngày kết thúc'),
    ('Tá»\u0089 lá»\u0087', 'Tỉ lệ'),
    ('tá»\u0089 lá»\u0087', 'tỉ lệ'),
    ('Ä\x90iá»\u0081u kiá»\u0087n', 'Điều kiện'),

    # Payment modal
    ('Sá»\u0091 dÆ° ná»£', 'Số dư nợ'),
    ('tiá»\u0081n', 'tiền'),
    ('hoÃ n', 'hoàn'),
    ('phiáº¿u', 'phiếu'),
    ('Phiáº¿u', 'Phiếu'),
    ('tráº£', 'trả'),

    # Transfers
    ('YÃªu cáº§u chuyá»\u0083n hÃ\xa0ng', 'Yêu cầu chuyển hàng'),
    ('Ä\x90iá»\u0081u chuyá»\u0083n hÃ\xa0ng tá»\u0093n kho', 'Điều chuyển hàng tồn kho'),
    ('Cá»­a hÃ\xa0ng', 'Cửa hàng'),
    ('cá»­a hÃ\xa0ng', 'cửa hàng'),
    ('Æ¯u tiÃªn', 'Ưu tiên'),
    ('NgÃ\xa0y cáº§n', 'Ngày cần'),
    ('Kho chá»\u0089 Ä\u0091á»\u008bnh', 'Kho chỉ định'),
    ('Chá»\u0089 Ä\u0091á»\u008bnh', 'Chỉ định'),
    ('chá»\u0089 Ä\u0091á»\u008bnh', 'chỉ định'),
    ('Chi tiáº¿t', 'Chi tiết'),
    ('Gá»­i', 'Gửi'),
    ('Xuáº¥t kho', 'Xuất kho'),
    ('Nháº­n hÃ\xa0ng', 'Nhận hàng'),
    ('Cháº¥p nháº­n', 'Chấp nhận'),
    ('XÃ¡c nháº­n', 'Xác nhận'),
    ('SL yÃªu cáº§u', 'SL yêu cầu'),
    ('SL duyá»\u0087t', 'SL duyệt'),
    ('SL chuyá»\u0083n', 'SL chuyển'),
    ('SL tá»\u0093n', 'SL tồn'),
    ('CH Ä\u0091Ã­ch', 'CH đích'),

    # Misc
    ('MÃ´ táº£', 'Mô tả'),
    ('Loáº¡i', 'Loại'),
    ('Sá»\u0091 lÆ°á»£ng', 'Số lượng'),
    ('NgÃ\xa0y táº¡o', 'Ngày tạo'),
    ('Táº¡o', 'Tạo'),
    ('Ä\u0091', 'đ'),
    ('HÃ ng tá»\u0093n kho', 'Hàng tồn kho'),

    # Handle remaining accent chars individually
    ('Ã¡', 'á'),
    ('Ã ', 'à'),
    ('áº£', 'ả'),
    ('Ã£', 'ã'),
    ('áº¡', 'ạ'),
    ('Äƒ', 'ă'),
    ('áº¯', 'ắ'),
    ('áº±', 'ằ'),
    ('áº³', 'ẳ'),
    ('áºµ', 'ẵ'),
    ('áº·', 'ặ'),
    ('Ã¢', 'â'),
    ('áº¥', 'ấ'),
    ('áº§', 'ầ'),
    ('áº©', 'ẩ'),
    ('áº«', 'ẫ'),
    ('áº­', 'ậ'),
    ('Ã©', 'é'),
    ('Ã¨', 'è'),
    ('áº»', 'ẻ'),
    ('áº½', 'ẽ'),
    ('áº¹', 'ẹ'),
    ('Ãª', 'ê'),
    ('áº¿', 'ế'),
    ('á»\u0081', 'ề'),
    ('á»\u0083', 'ể'),
    ('á»\u0085', 'ễ'),
    ('á»\u0087', 'ệ'),
    ('Ã­', 'í'),
    ('Ã¬', 'ì'),
    ('á»\u0089', 'ỉ'),
    ('Ä©', 'ĩ'),
    ('á»\u008b', 'ị'),
    ('Ã³', 'ó'),
    ('Ã²', 'ò'),
    ('á»\u008f', 'ỏ'),
    ('Ãµ', 'õ'),
    ('á»\u008d', 'ọ'),
    ('Ã´', 'ô'),
    ('á»\u0091', 'ố'),
    ('á»\u0093', 'ồ'),
    ('á»\u0095', 'ổ'),
    ('á»\u0097', 'ỗ'),
    ('á»\u0099', 'ộ'),
    ('Æ¡', 'ơ'),
    ('á»\u009b', 'ớ'),
    ('á»\u009d', 'ờ'),
    ('á»\u009f', 'ở'),
    ('á»¡', 'ỡ'),
    ('á»£', 'ợ'),
    ('Ãº', 'ú'),
    ('Ã¹', 'ù'),
    ('á»§', 'ủ'),
    ('Å©', 'ũ'),
    ('á»¥', 'ụ'),
    ('Æ°', 'ư'),
    ('á»©', 'ứ'),
    ('á»«', 'ừ'),
    ('á»­', 'ử'),
    ('á»¯', 'ữ'),
    ('á»±', 'ự'),
    ('Ã½', 'ý'),
    ('á»³', 'ỳ'),
    ('á»·', 'ỷ'),
    ('á»¹', 'ỹ'),
    ('á»µ', 'ỵ'),
    ('Ä\u0091', 'đ'),
    ('Ä\x90', 'Đ'),

    # Uppercase
    ('Ã\x81', 'Á'),
    ('Ã€', 'À'),
    ('áº¢', 'Ả'),
    ('Ãƒ', 'Ã'),
    ('áº ', 'Ạ'),
    ('Ä\x82', 'Ă'),
    ('Ã‚', 'Â'),
    ('Ã‰', 'É'),
    ('Ãˆ', 'È'),
    ('ÃŠ', 'Ê'),
    ('Ã\x8d', 'Í'),
    ('ÃŒ', 'Ì'),
    ('Ã"', 'Ó'),
    ('Ã'', 'Ò'),
    ('Ã"', 'Ô'),
    ('Ã•', 'Õ'),
    ('Æ ', 'Ơ'),
    ('Ãš', 'Ú'),
    ('Ã™', 'Ù'),
    ('Æ¯', 'Ư'),
    ('Ã\x9d', 'Ý'),

    # Common words cleanup
    ('NhÃ ', 'Nhà'),
    ('hÃ ng', 'hàng'),
    ('HÃ ng', 'Hàng'),
    ('bÃ¡n', 'bán'),
    ('BÃ¡n', 'Bán'),
    ('tiÃªn', 'tiên'),
    ('lÃ½', 'lý'),
    ('Ã¢n', 'ân'),
]

for garbled, correct in replacements:
    data = data.replace(garbled, correct)

open(f, 'w', encoding='utf-8', newline='\n').write(data)

# Verify
v = open(f, 'r', encoding='utf-8').read()
log = open('fix_log.txt', 'w', encoding='utf-8')
log.write('Line 6: ' + v.split('\n')[5][:100] + '\n')
log.write('Line 84: ' + v.split('\n')[83][:100] + '\n')
log.write('Line 85: ' + v.split('\n')[84][:100] + '\n')
log.write('DONE\n')
log.close()

